### ISSUE TITLE
Error- Module 1-  Exercise 1: Creating users in Azure AD

### ISSUE THREAD

**Issue by vikasmct** [MicrosoftLearning/MD-102T00-Microsoft-365-Endpoint-Administrator#11]
# Module:1-  Exercise 1: Creating users in Azure AD## Lab/Demo: 00
#### Step -5 ( This is correct PowerShell command )

Description of issue- Command is in correct

Correct PS command

New-MsolUser -DisplayName "Cody Godinez" -UserPrincipalName cgodinez@M365x21507465.onmicrosoft.com  -Password "pass@word1" -FirstName "Cody" -LastName "Godinez" -ForceChangePassword $false -UsageLocation "US" -Title "Sales Rep" -Department "Sales"

**Comment by MSFT-rstearman** [comment]
Hello Vikasmct,
The only change to the code in the labs and the one you provided is the order that you entered the properties in and that you updated the password and UPN. Note that the @yourtenant.onmicrosoft.com is there to act as a placeholder for your tenant. Depending on your lab provider, the tenant address will be different for each learner.
