### ISSUE TITLE
Configuring Disk Encryption Using Intune - 

### ISSUE THREAD

**Issue by Kiyani1** [MicrosoftLearning/MD-102T00-Microsoft-365-Endpoint-Administrator#12]
#### Step: 07

Description of issue

The option to select PIN does not show up. Please guide me on what I might be doing wrong here.

![image](https://github.com/MicrosoftLearning/MD-102T00-Microsoft-365-Endpoint-Administrator/assets/98971092/bb4651b2-09f4-4d67-b4d0-0e3fe2c33326)

Repro steps:

1. Perform all prerequisite steps.
1. On step 7 option to select PIN does not show up.

**Comment by MSFT-rstearman** [comment]
Hello Kiyani1,
Thank you for submitting this to us. I will review this and let you know soon.
