### ISSUE TITLE
Refreshing Windows with Autopilot Reset and Self Deploying Mode - WS4 stuck after autopilot reset

### ISSUE THREAD

**Issue by Kiyani1** [MicrosoftLearning/MD-102T00-Microsoft-365-Endpoint-Administrator#13]
#### Step: 00

Description of issue

WS4 stuck on Device preparation after autopilot reset. I have waited around 6 hours but it has not moved forward tried resetting the VM as well.

However, on Intune, it shows that autopilot reset is completed and VM is given a new name as well using the Contoso-%RAND:2% 

![image](https://github.com/MicrosoftLearning/MD-102T00-Microsoft-365-Endpoint-Administrator/assets/98971092/10c3551d-eacd-4eff-84e9-98cc2d54dd7d)

![image](https://github.com/MicrosoftLearning/MD-102T00-Microsoft-365-Endpoint-Administrator/assets/98971092/3ec9e65a-fca5-4892-bd7d-356b6791b22a)

Repro steps:

1. Perform all prerequisite steps.
1. See that WS4 is stuck as shown in the screenshot

**Comment by WigF1** [comment]
See #49 - this lab has never worked properly and should be removed. Self-deploy only works with a physical TPM, not virtuals.

**Comment by MSFT-rstearman** [comment]
We are currently working on an update for the course and will be replacing this lab with an alternative one.
