### ISSUE TITLE
Azure AD admin center

### ISSUE THREAD

**Issue by WigF1** [MicrosoftLearning/MD-102T00-Microsoft-365-Endpoint-Administrator#14]
Issue #2 was closed for some reason.

The updates made last week have not changed the wording. It is the Entra admin center, not the Azure AD admin center.

For example:

![image](https://github.com/MicrosoftLearning/MD-102T00-Microsoft-365-Endpoint-Administrator/assets/12164329/5fa9eeae-1e9f-4eba-830c-842b42d77917)

**All** references to the Azure AD admin center need to be modified.

**Comment by craigbeeremct** [comment]
To add to this, the Microsoft 365 Admin Center has changed its label.

0101-Managing Identities in Azure AD.md, Ex 1, Task 1, Step 10.
Replace:
In the Navigation pane, under Admin centers select Azure Active Directory. The Microsoft Entra admin center opens.
With:
In the Navigation pane, under Admin centers select Identity. The Microsoft Entra admin center opens.

**Comment by MSFT-rstearman** [comment]
Closing this as we corrected this issue in a previous ticket
