### ISSUE TITLE
Rename Microsoft Endpoint Manager admin center

### ISSUE THREAD

**Issue by WigF1** [MicrosoftLearning/MD-102T00-Microsoft-365-Endpoint-Administrator#15]
Any and all references to 'Microsoft Endpoint Manager admin center' need to be changed to 'Intune admin center'

**Comment by craigbeeremct** [comment]
At least until Microsoft rename it something different next month. :-)

**Comment by craigbeeremct** [comment]
The link in the Admin Centers section of the Microsoft 365 Admin Center (admin.microsoft.com) is still labelled "Endpoint Manager".

**Comment by MSFT-rstearman** [comment]
Closing this out as these changes have been made.
