### ISSUE TITLE
Replace endpoint.microsoft.com URIs

### ISSUE THREAD

**Issue by WigF1** [MicrosoftLearning/MD-102T00-Microsoft-365-Endpoint-Administrator#3]
# Module: All
## Lab/Demo: All

Description of issue

As announced over 6 months ago, the product name is Microsoft Intune. As such, the recommended URI to reflect the Intune admin center should be https://intune.microsoft.com

All URIs for https://endpoint.microsoft.com need to be replaced with https://intune.microsoft.com

**Comment by MSFT-rstearman** [comment]
I am currently updating the labs to reflect this change.
