### ISSUE TITLE
module 4

### ISSUE THREAD

**Issue by WarrenAJ** [MicrosoftLearning/MD-102T00-Microsoft-365-Endpoint-Administrator#30]
# Module: 04
#### Step: 00

Description of issue
It should be noted that the deployment of apps to the company portal website is notoriously slow. I've literally never had it work as written. EVENTUALLY, the Remote Desktop app lolls onto the page in its own good time. I always tell my students to move on and circle back to check later. But we really should find out WHY this is so slow, and engineer around it.  

Repro steps:

1.
1.
1.

**Comment by WarrenAJ** [comment]
Ok, so this does work eventually (but I knew it EVENTUALLY would). Took mine 15 minutes. That's about enough time to configure M365 in the next part of the lab. 

SUGGEST:

In Ex1 task 4, stop at step9 with comment : We will install the app and check on its status after the next exercise.

Then, in ex 2 remove task 4.

Create Exercise 3: INstalling and verifying apps

Add the steps to install Rremote Desktop from Ex 1 Task 4 (as it will now be accessble)
Then add the steps from Ex 2 task 4 to verify M365 (which in turn gives that app time to deploy).

-Andy

**Comment by TommyKobber** [comment]
Why are we having a lab on Microsoft Store for Business when it will retire soon and always is reduced in functionality? It's not an exam subject either

**Comment by WarrenAJ** [comment]
The latest version of the labs does not include a Store for Business lab.

**Comment by MSFT-rstearman** [comment]
Added notes to lab instructions.
