### ISSUE TITLE
Parsing Issue in 3 Labs

### ISSUE THREAD

**Issue by tumultuous1** [MicrosoftLearning/MD-102T00-Microsoft-365-Endpoint-Administrator#4]
Module 301 (Exercise 1, Task 4, Step 5)
Module 801 (Task 1, Step 13) (Task 2, Steps 7,11,12,13
Module 803 (Task 1, Steps 8,14)

The backticks need to have enough spaces to match the code.  This will cause issues with ALHs when the .md is parsed.  Example in screenshot below.                 

![image](https://user-images.githubusercontent.com/103527215/235154759-9380e71c-a99f-4c62-8a6e-41aa351dc84d.png)

**Comment by MSFT-rstearman** [comment]
Hello tumultuous1,
Thank you for this comment. While reviewing this, I am not able to replicate the issue, can you please let me know which ALH's are having these issues so we can further investigate. Also, can you provide your thoughts on a solution via a pull request so we can further test.

Thank you and I look forward to your feedback.

**Comment by TesterTesterson1004** [comment]
The issue as I see it, is that by not implementing code blocks _flush_ w/code, and instead including 4 spaces/indent *within* the code block, what we are saying is that (when rendered, even within Github) ...we are adding those 4 spaces into the command.

In GH, we thus end up with a weirdly formatted code block with extraneous leading spaces:

![image](https://github.com/MicrosoftLearning/MD-102T00-Microsoft-365-Endpoint-Administrator/assets/49700217/10c6842d-b98a-4bf0-bcf1-6707391832a1)

Contrast this against other code blocks within this repo where code blocks are flush, and thus have no extraneus leading spaces:

![image](https://github.com/MicrosoftLearning/MD-102T00-Microsoft-365-Endpoint-Administrator/assets/49700217/de1e3907-f0b4-4182-9abf-2837e989bc77)

So, when the student clicks to autotype this code block into the VM - that results in 4 extra spaces being typed into the Command-window within the VM, and only then the command we actually want.  Believe it or not, Students and Instructors will call in tickets on this behavior:  In addition to being weirdly formatted (one would never intentionally type in leading spaces before typing the desired command) ...in some cases, particular when things like Intellisense may be enabled in Cloudshell, or other apps such as VS Code, the extraneous 4 spaces typed into the app can cause issues.

I understand, of course, that all ALHs may not use markdown parsers identical to Github's, but in any case....consistency of formatting within a repo's Instructions set is also highly desirable.  Parser differences can be corrected by ALHs to fix...but if something like a code block formatting varies throughout the .md documents - sometimes formatted flush left, sometimes formatted with extraneous spaces, etc., correcting it can become a chore in and of itself for ALHs.

**Comment by MSFT-rstearman** [comment]
Thank you for the explanation.
I will review the code and make the necessary changes.
