### ISSUE TITLE
0802-Refreshing Windows with Autopilot Reset and Self Deploying Mode.md

### ISSUE THREAD

**Issue by WigF1** [MicrosoftLearning/MD-102T00-Microsoft-365-Endpoint-Administrator#49]
# Module: 08
## Lab/Demo: 02

Description of issue

This entire lab will fail every time as self-deploying mode is not supported for virtual TPMs, specifically Hyper-V. This lab needs to be removed from the course.

From this link : https://learn.microsoft.com/en-us/mem/autopilot/self-deploying

![image](https://github.com/MicrosoftLearning/MD-102T00-Microsoft-365-Endpoint-Administrator/assets/12164329/f811bd40-6d57-4714-8f8d-69da05009010)

**Comment by WigF1** [comment]
Further to my initial comment, when you complete Lab 0802, this is the error you see in the Intune portal.

![image](https://github.com/MicrosoftLearning/MD-102T00-Microsoft-365-Endpoint-Administrator/assets/12164329/b44699e9-bc95-487b-ac1d-f73c3df06c18)

All that happened is the machine was reset. Again, this lab (0802) needs to be removed from the course.

**Comment by MSFT-rstearman** [comment]
Closing as this was a duplicate to several other related bugs. We are working to create an alternative lab
