### ISSUE TITLE
0404-Deploy Apps using Microsoft Store for Business

### ISSUE THREAD

**Issue by WigF1** [MicrosoftLearning/MD-102T00-Microsoft-365-Endpoint-Administrator#5]
# Module: 04
## Lab/Demo: 04

Description of issue

Taken from https://learn.microsoft.com/en-us/mem/intune/fundamentals/in-development

On April 30, 2023, Intune will disconnect Microsoft Store for Business services. Microsoft Store for Business and Education apps won't be able to sync with Intune and the connector page will be removed from the Intune admin center.

This entire lab needs to be re-written to use Mirosoft Store (new) instead of the current instructions.

**Comment by MSFT-rstearman** [comment]
Thank you for your response. Microsoft Store for Business is not completely retired.
Stages of retirement
In April 2023 we will begin ending support for the Microsoft Store for Business experience in Intune. This will occur in several stages:

On April 30, 2023, Intune will disconnect Microsoft Store for Business services. Microsoft Store for Business and Education apps will no longer be able to sync with Intune and the connector page will be removed from the Intune admin center.
On June 15, 2023, Intune will stop enforcing online and offline Microsoft Store for Business and Education apps on devices. Downloaded applications will remain on the device with limited support. Users may still be able to access the app from their device, but the app will no longer be managed. Existing synced Intune app objects will remain to allow admins to view the apps that had been synced and their assignments. Additionally, you will longer be able to sync apps via the Microsoft Graph API [syncMicrosoftStoreForBusinessApps](https://learn.microsoft.com/graph/api/intune-shared-deviceappmanagement-syncmicrosoftstoreforbusinessapps?view=graph-rest-beta) and related API [properties](https://learn.microsoft.com/graph/api/resources/intune-shared-deviceappmanagement?view=graph-rest-beta#properties) will display stale data.
On September 15, 2023, Microsoft Store for Business and Education apps will be removed from the Intune admin center. Apps on the device will remain until intentionally removed. The Microsoft Graph API [microsoftStoreForBusinessApp](https://learn.microsoft.com/graph/api/resources/intune-apps-microsoftstoreforbusinessapp?view=graph-rest-1.0) will no longer be available about a month later. 

We are working on a lab to replace this one. For more information on the retirement of Microsoft for Business, Please visit the link below.

https://techcommunity.microsoft.com/t5/windows-it-pro-blog/update-to-intune-integration-with-the-microsoft-store-on-windows/ba-p/3585077

**Comment by WigF1** [comment]
@MSFT-rstearman You missed my point entirely.

As you can no longer connect the Store for Business to Intune, Lab 0404 **cannot** be performed and, as such, should be removed from the labs.

**Comment by tumultuous1** [comment]
In a recent QA, we have also experienced this same issue and this is a roadblock.   What is the workaround?
