### ISSUE TITLE
Slight UI Change

### ISSUE THREAD

**Issue by IamUser1337** [MicrosoftLearning/MD-102T00-Microsoft-365-Endpoint-Administrator#50]
[0101-Managing Identities in Azure AD.md](https://github.com/MicrosoftLearning/MD-102T00-Microsoft-365-Endpoint-Administrator/blob/master/Instructions/Labs/0101-Managing%20Identities%20in%20Azure%20AD.md)
#### Step: 06

Close out of the **Authentication complete** tab in and then minimize **Microsoft Edge**

Should be 

Close out of the **Authentication complete** tab  and then minimize **Microsoft Edge**

**Comment by IamUser1337** [comment]
I opened a few issues just now but I wanted to let you know that I was impressed with the overall quality of the course updates, Nice work on this one 👍🏽

**Comment by WigF1** [comment]
I'm currently going through every lab and making corrections where needed. I've added this into my fork and will include it in the resulting PR

**Comment by WigF1** [comment]
PR has been submitted #57

**Comment by MSFT-rstearman** [comment]
Thank you for your feedback. I apologize for the delayed response. This was resolved in a previous update.
