### ISSUE TITLE
0501 Issues

### ISSUE THREAD

**Issue by IamUser1337** [MicrosoftLearning/MD-102T00-Microsoft-365-Endpoint-Administrator#53]
[0501-Configuring multi-factor authentication.md](https://github.com/MicrosoftLearning/MD-102T00-Microsoft-365-Endpoint-Administrator/blob/master/Instructions/Labs/0501-Configuring%20multi-factor%20authentication.md)

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/BRANDO~1.LET/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/BRANDO~1.LET/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link=blue vlink=purple>

Exercise   # | Task # | Step # | Issues   Identified
-- | -- | -- | --
1 | 1 | 5 | Alex's password did not work. Went ahead and reset it to the   Tenant password to proceed with lab
2 | 2 | 11 | Select No cloud apps, actions,   or authentication contexts selected and then click Select apps.          Should be           Select No target resources selected and then click select apps.

</body>

</html>

**Comment by maquinl** [comment]
Hi @IamUser1337 

learners may need to reset the password of pre-created accounts inside the provided tenant. Please follow the below steps to reset the account passwords:

Log into admin.microsoft.com with the credentials found in your resources tab.

On Left side bar, select Users to expand the field and then select Active Users.

Select the check box next to Display Name to select all users.

Deselect the check boxes next to MOD Administrator and Microsoft Service Account.

Do not change the MOD Administrator or Microsoft Service Account passwords.
Select Reset Password from the middle action ribbon.

In the Reset Password Pane, unselect all options and enter a new password in the field provided.

Some lab hosting providers call this out already, but we will add instructions towards the beginning of the lab series to proactively do this. This will also resolve the other 2 open issues #52 & #51 

The wording in Exercise 2 task 2 step 11 has also been updated.
