### ISSUE TITLE
Missing Encryption Options in UI

### ISSUE THREAD

**Issue by IamUser1337** [MicrosoftLearning/MD-102T00-Microsoft-365-Endpoint-Administrator#54]
[0602-Configuring Disk Encryption Using Intune.md](https://github.com/MicrosoftLearning/MD-102T00-Microsoft-365-Endpoint-Administrator/blob/master/Instructions/Labs/0602-Configuring%20Disk%20Encryption%20Using%20Intune.md)

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/BRANDO~1.LET/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/BRANDO~1.LET/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<style>

</style>
</head>

<body link=blue vlink=purple>

Exercise   # | Task # | Step # | Issues   Identified
-- | -- | -- | --
1 | 1 | 10 | Required encryption options are missing from steps.

</body>

</html>

![Mod18_Shot1](https://github.com/MicrosoftLearning/MD-102T00-Microsoft-365-Endpoint-Administrator/assets/72228536/e94cf8be-0729-437e-b503-6093ec10e70e)

**Comment by WigF1** [comment]
See #57

**Comment by WigF1** [comment]
As it has now been 3 months and the 'new' UI is here to stay, the lab steps need re-writing.

**Comment by MSFT-rstearman** [comment]
Closed as changes were made to the course to match the UI
