### ISSUE TITLE
0502-Configuring self-service password reset

### ISSUE THREAD

**Issue by WigF1** [MicrosoftLearning/MD-102T00-Microsoft-365-Endpoint-Administrator#55]
# Module: 05
#### Step: 14

Description of issue

Why are we having students enable the writeback for cloud sync when we have no provisioning agents installed, nor do we need any for the labs?

After enabling the option, every student will see the following error:

![image](https://github.com/MicrosoftLearning/MD-102T00-Microsoft-365-Endpoint-Administrator/assets/12164329/f58f63e1-cdaf-4cc8-aba9-fd3c1422235a)

Why was this step included in the instructions? It should be removed.

**Comment by Srikanthssp** [comment]
Yes, we are also facing the same issue.

**Comment by WigF1** [comment]
I just tell students to ignore the step. It's pointless.

**Comment by MSFT-rstearman** [comment]
Thank you for the feedback. I have gone ahead and updated the course to reflect these changes.
