### ISSUE TITLE
0801-Deploying Windows with AutoPilot

### ISSUE THREAD

**Issue by WigF1** [MicrosoftLearning/MD-102T00-Microsoft-365-Endpoint-Administrator#56]
# Module: 08
## Lab/Demo: 01

Description of issue

The 'important' note at the start of this lab makes no sense.

![image](https://github.com/MicrosoftLearning/MD-102T00-Microsoft-365-Endpoint-Administrator/assets/12164329/eb2079a2-3720-4b39-8f85-e29b355f902e)

SEA-W10-CL3 is also a Virtual Machine, it also has a Virtual TPM. The only thing we can't do from *any* VM in the labs is the Autopilot Reset + self-deploying. 

We *can* use SEA-WS4 for the initial Autopilot deployment in the same way we did in MD-101 for years. In my opinion, this note should be removed and we should continue to use SEA-WS4 for lab 0801.

**Comment by WigF1** [comment]
@maquinl 

I see you updated Lab 0801 with this commit : https://github.com/MicrosoftLearning/MD-102T00-Microsoft-365-Endpoint-Administrator/commit/da8373a7d999387bc2d0ddbcc5e06d5cce90ccf7

The text still makes no sense. Windows 11 works fine for the Autopilot user-driven scenario.

**Comment by maquinl** [comment]
@WigF1 thanks for the feedback, we will review this further and update the lab.

**Comment by craigbeeremct** [comment]
I've just been through the lab simultaneously on SEA-WS4 and SEA-WIN10-CL3 and it worked fine.

Well, I say "simultaneously" but SEA-WS4 sat at 1% until the other machine had almost finished its installation.

**Comment by WigF1** [comment]
It also works on SEA-WS1, SEA-WS2 and SEA-WS3 like it always did. As I mentioned in #49 it's only the self-deploy that we can't do with a Virtual TPM. This lab works fine.

**Comment by maquinl** [comment]
@WigF1 - thanks for bump. Tagging the content dev, @MSFT-rstearman for further review.

**Comment by MSFT-rstearman** [comment]
We are currently reviewing the course and will create an alternative to this lab.
