### ISSUE TITLE
0101 - Task 1 Step 17

### ISSUE THREAD

**Issue by kramit** [MicrosoftLearning/MD-102T00-Microsoft-365-Endpoint-Administrator#6]
0101 - Task 1 Step 17

Literally the first lab, Pa55w.rd is not a valid password for 365 it is not complex enough. Did anyone from MS even bother to test??!?

![image](https://github.com/MicrosoftLearning/MD-102T00-Microsoft-365-Endpoint-Administrator/assets/5239228/23ee2078-73b4-4e6a-8ce5-68eea0b4de3c)

**Comment by MSFT-rstearman** [comment]
I have updated the passwords to meet the requirements.
