### ISSUE TITLE
0101-Managing Identities in Azure AD.md - curly quotes

### ISSUE THREAD

**Issue by craigbeeremct** [MicrosoftLearning/MD-102T00-Microsoft-365-Endpoint-Administrator#60]
# Lab/Demo: 0101-Managing Identities in Azure AD.md

#### Step: 8

There are some curly quotes in the script, around the -DIsplayName parameter value. They need to be replaced with straight quotes (").

#### Step: 2

Same for the -DisplayName and -Description parameter values.

#### Step: 6

Same for the filter script.

**Comment by WigF1** [comment]
I've fixed these in #59 - just waiting for it to be merged.

**Comment by MSFT-rstearman** [comment]
This issue has been resolved.
