### ISSUE TITLE
Lab 0101, passwords too weak/common

### ISSUE THREAD

**Issue by TommyKobber** [MicrosoftLearning/MD-102T00-Microsoft-365-Endpoint-Administrator#61]
# Module: 01
#### Step: 15 and 30

The password suggested (Pa55w.rd1234) does not pass the requirements of not being too weak or too common

Repro steps:

1.
1.
1.

**Comment by craigbeeremct** [comment]
Any password that gets written into a lab will either end up being too common or known by threat actors.

Task 1 should have the same phrasing that task 2 has.

Step 15, 30: Next to Password, enter a complex password of your choice.

**Comment by MSFT-rstearman** [comment]
We have not been able to recreate this issue. Can you please provide screen shot so we can review this further.

**Comment by TommyKobber** [comment]
![password](https://github.com/MicrosoftLearning/MD-102T00-Microsoft-365-Endpoint-Administrator/assets/57709815/00a1546c-fcf8-496c-813d-cd83b76b0177)

**Comment by hbud** [comment]
Why not use the tenant admin password in this course? We change the password in many other courses to that one, even in the SC courses. In the lab interface students can easily select that password. Would make the labs in all courses more consistant. Not a secure option in the real world, but could work in the course.

**Comment by maquinl** [comment]
The following note has been added under steps 15 & 30:

If you receive an error message stating that this password in weak or commonly used, enter the tenant password found under the Resources tab of this lab profile. Alternatively, you can enter a complex password of your choice.

Either option should work.
