### ISSUE TITLE
More Azure AD --> Entra rename UI changes

### ISSUE THREAD

**Issue by craigbeeremct** [MicrosoftLearning/MD-102T00-Microsoft-365-Endpoint-Administrator#62]
# Practice Lab: Configuring and managing Azure AD Join

Exercise 1: Configuring Azure AD Join
Task 3: Validate Azure AD Join
Step 10

Replace with:
In Microsoft Edge, in the Microsoft Entra admin center, expand Identity.

Exercise 2: Configuring Hybrid Azure AD Join
Task 4: Verify the Azure AD registration
Step 9

Replace with:
Expand Identity, and then select Devices > All devices.

# Practice Lab: Manage Azure AD device registration

Exercise 1: Configuring Azure AD device registration
Task 1: Configure Azure AD device registration
Step 4

Replace with:
In the Microsoft Entra admin center, in the navigation pane, expand Identity.

Exercise 1: Configuring Azure AD device registration
Task 3: Validate Azure AD registration
Step 6

Replace with:
In Microsoft Edge, in the Microsoft Entra admin center, expand Identity.

# Practice Lab: Manage Device Enrollment into Intune

Task 1: Review and assign licenses for device management
Step 4

Replace with:
In the navigation pane, expand Identity and then select Show more.

Task 1: Review and assign licenses for device management
Step 9

Replace with:
In the Entra admin center navigation pane, under Identity, select Users > All users.

# Practice Lab: Enrolling devices into Microsoft Intune

Task 4: Verifying device enrollment in the Intune console
Step 8

Replace with:
In the Microsoft Entra admin center, expand Identity.

# Practice Lab: Configuring Multi-factor Authentication

Exercise 2: Configure multi-factor authentication using conditional access
Task 2: Configure conditional access with MFA
Step 4

Replace with:
In the Microsoft Entra admin center, expand Identity.

# Practice Lab: Deploying Windows with Autopilot

Task 1: Create group in Azure AD
Step 4

Replace with:
In the navigation pane, Expand Identity.

Task 5: Verify Autopilot deployment
Step 14

Replace with:
In the Microsoft Entra admin center, select Identity, select Devices and then select All devices.

**Comment by WigF1** [comment]
@MSFT-rstearman @maquinl 

Guys, given most of these were remedied in #59 that was summarily closed, when can we expect the changes?!!??! Our students deserve the best experience and, at the moment, they're not getting it. 

This entire repo needs a clean-up lest it become another MD-101 wasteland.

**Comment by MSFT-rstearman** [comment]
A majority of these changes have been completed and pushed to master. We are still reviewing for any additional changes that might need to be updated due to the rebranding.
