### ISSUE TITLE
Practice Lab: Managing Identities in Azure AD - remove Get-MgUser licensing note

### ISSUE THREAD

**Issue by craigbeeremct** [MicrosoftLearning/MD-102T00-Microsoft-365-Endpoint-Administrator#64]
# Practice Lab: Managing Identities in Azure AD
#### Step 9

The Get-MgUser cmdlet (in version 2.3.0 of Microsoft.Graph.Users) does not return the isLicensed property unless you ask for it.

Replace:

Verify that the list of users from your tenant is displayed. Also take note of which users have a license assigned. Any user with the isLicensed value of False has not been assigned a license.

With:

Verify that the list of users from your tenant is displayed. 

-Or-

Replace the PowerShell code in step 9 with:

Get-MgUser  -Property DisplayName, UserPrincipalName, AssignedLicenses, AssignedPlans, LicenseAssignmentStates, LicenseDetails | Select-Object DisplayName, UserPrincipalName, AssignedLicenses, AssignedPlans, LicenseAssignmentStates, LicenseDetails

**Comment by MSFT-rstearman** [comment]
I have reviewed this and added your suggested changes.
