### ISSUE TITLE
0401-Deploying cloud apps using Intune.md/Task 04/ Step 12

### ISSUE THREAD

**Issue by Nimra-Maryam** [MicrosoftLearning/MD-102T00-Microsoft-365-Endpoint-Administrator#65]
# Lab/Demo: 0401
#### Step: 12

Not able to install the Microsoft Remote Desktop App as the synchronization going into a pending state. 
Waited for approximately 30 hours but it remains in the pending state.

![image](https://github.com/MicrosoftLearning/MD-102T00-Microsoft-365-Endpoint-Administrator/assets/133017642/4d721570-0ef0-47ab-86f6-a7d9ebae13bb)

**Comment by MSFT-rstearman** [comment]
I am unable to duplicate this issue, please provide additional detail if you continue to encounter this issue.

**Comment by MSFT-rstearman** [comment]
I am unable to duplicate this issue, please provide additional detail if you continue to encounter this issue.
