### ISSUE TITLE
Yet more Azure AD / Entra changes - needs addressing

### ISSUE THREAD

**Issue by WigF1** [MicrosoftLearning/MD-102T00-Microsoft-365-Endpoint-Administrator#67]
Re the now closed #62 

I submitted a PR on July 22 that included many fixes. The PR was rejected because of conflicts with 'upcoming' changes due to naming. Craig opened another issue asking for clarification because changes still needed to happen. That (#62) was also closed after apparently checking.

![image](https://github.com/MicrosoftLearning/MD-102T00-Microsoft-365-Endpoint-Administrator/assets/12164329/4ab220f2-ea0a-4132-aa6d-6636b9b373f7)

Here we are *WEEKS* later since 62 and some of my changes from July 22 - OVER 3 MONTHS AGO - still haven't made it in.

Lab titles, scenarios, UI changes, step changes all need to be made.

I don't mind doing it, I *want* to do it. Despite the best efforts to keep this out of date, I want it up to date. But @MSFT-rstearman and @maquinl and whomever else at Microsoft is concerned needs to work with us. 

If I go through these lab steps and submit another large PR with correct names, descriptions, terms etc, is that something that will be merged or are there 'updates' planned that *never* eventuate?

**Comment by MSFT-rstearman** [comment]
@WigF1 sorry for the delay in responding. Yes, I did reject the pull request as it would have been a conflict with the updates I was working on. I did however port your suggestions over to the changes I was making. 
I do appreciate that you are willing to make Pull request, and they are extremely helpful. If there are no conflicts at the time they are submitted and they are tested, I will approve them. Please don't stop helping to make this a great course and we are actively working hard to make it the best quality. Thank you again for the assistance you bring to this course.
