### ISSUE TITLE
Lab instructions - Ellipsis vs ellipse

### ISSUE THREAD

**Issue by thismre** [MicrosoftLearning/MD-102T00-Microsoft-365-Endpoint-Administrator#68]
MD-102 Lab instructions:
Labs 0305, 0801, and 0802 all mention that students may have to click an ELLIPSE. 
This should say ELLIPSIS. An ellipse is a geometric shape. An ellipsis is a mark of punctuation consisting of three horizontal dots. ( ... )
Likely other lab instructions from other classes have this issue, should be quite easy to search all at once and correct.  Just a thought... :)

**Comment by thismre** [comment]
I see that many of the lab instructions have been adjusted to say ELLIPSES (with no acknowledgement of the above issue).  This is the plural of ELLIPSIS.  The instructions should refer to clicking an ellipsis.

**Comment by MSFT-rstearman** [comment]
Thank you for the feedback. I have gone ahead and made these corrections.
