### ISSUE TITLE
0101 all powershell command bad double quotes

### ISSUE THREAD

**Issue by kramit** [MicrosoftLearning/MD-102T00-Microsoft-365-Endpoint-Administrator#7]
New-MsolUser –UserPrincipalName cgodinez@yourtenant.onmicrosoft.com -DisplayName “Cody Godinez” -FirstName “Cody” -LastName “Godinez” -Password ‘Pa55w.rd’ -ForceChangePassword $false -UsageLocation “US” -Title "Sales Rep" -Department "Sales"

look at this command here. There are 2 different types of double quotes

 “US” -Title "Sales Rep" 
 
 the double quotes around US are NOT VALID in the powershell shell in window server, the VMs that are provided for this course.... The double quotes around "sales red" are fine
 
 Need to do a find and replace and fix all these quotes so the powershell commands actually work correctly 
 
Who is the product owner for this course??

**Comment by MSFT-rstearman** [comment]
Hello Kramit,

I have tested this script and found no issues with it. On execution, the script does as it is intended.

**Comment by kramit** [comment]
no,

there are literally 2 different sets of double quotes here so when they are pasted into a shell on a windows server with PS 5.1 they will no render correctly.

You did nothing here, I even provided a screenshot showing the exact problem

Fix the quotes please
