### ISSUE TITLE
Powershell 7 issues

### ISSUE THREAD

**Issue by Wallaho** [MicrosoftLearning/MD-102T00-Microsoft-365-Endpoint-Administrator#73]
# Module: 01
#### Step: 2

On [SEA-SVR1], click into the Windows Search bar and then type *password*. Right click on PowerShell 7 and then select Run as Administrator.

In the PowerShell 7 window, type the following command, and then press Enter. If prompted, enter [Y] at the NuGet and repository messages:

No need to run as Administrator OR running as Administrator does not work.

**Comment by MSFT-rstearman** [comment]
We have not been able to duplicate this issue. Can you attach error messages for further review?

**Comment by maquinl** [comment]
@Wallaho - In testing, running PowerShell in an elevated instance or not, this works. If there is a specific error message you see please re-open this issue and attach a screenshot. Thanks!
