### ISSUE TITLE
The Device Enrollment section of Intune has changed.

### ISSUE THREAD

**Issue by SN7400** [MicrosoftLearning/MD-102T00-Microsoft-365-Endpoint-Administrator#77]
# Module: 02
#### Step: 03-04

This section of the Intune UI has changed. This needs to be updated in a few other tasks and steps too.

Repro steps:

1. On step 3, instead of "Enroll devices", it should say "Enrollment".
2. On step 4, instead of "Windows enrollment", it should just skip to step 5 (Automatic Enrollment).

**Comment by MSFT-rstearman** [comment]
@SN7400 I will review this and make the necessary changes.
