### ISSUE TITLE
Intune interface for Policies has changed

### ISSUE THREAD

**Issue by SN7400** [MicrosoftLearning/MD-102T00-Microsoft-365-Endpoint-Administrator#79]
# Module: 03
#### Step: 05

The Intune interface for Policies has changed, so instructions are outdated. There may be other instances of this as well.

Repro steps:

1. On step 5, instead of "in the Policy section", it should say "in the Manage devices section".

**Comment by MSFT-rstearman** [comment]
@SN7400 I will review this and make the necessary changes.
