### ISSUE TITLE
0201 (preview) should no longer be there

### ISSUE THREAD

**Issue by kramit** [MicrosoftLearning/MD-102T00-Microsoft-365-Endpoint-Administrator#8]
step 11. (preview) should no longer be there

![image](https://github.com/MicrosoftLearning/MD-102T00-Microsoft-365-Endpoint-Administrator/assets/5239228/a99ca906-4744-4a9e-892b-c14fac050ec5)

**Comment by MSFT-rstearman** [comment]
Hello Kramit,

I could not fine any such statement in the code that would produce the data you provided in the screen shot. Here is a snippet of code that reference the step as it sits in the Repo.

Line 49 reads (11. In the **Additional local administrators on all Azure AD joined devices** section, select **Manage Additional local administrators on all Azure AD joined devices**. The Device Administrators page opens.)

Feel free to add a pull request if you find that there is a typo or a minor correction that need to be made. I will be happy to review it.
