### ISSUE TITLE
lab 5, MFA allready active

### ISSUE THREAD

**Issue by renaudwangler** [MicrosoftLearning/MD-102T00-Microsoft-365-Endpoint-Administrator#82]
#### Step: 6

On the test tenant provided by the lab platform (goDeploy in our case) some students have a conditional access policy applied (named "Multifactor authentication for partners and vendors) so the MFA is applied before they set it up...
Is it the same on other lab environments ?
Are you aware of any mean to bypass/change this (the policy can't be edited nor disabled)

**Comment by awillslo** [comment]
MS creates the tenancy template for Lab hosters to use.
What has been implemented in the template is a Conditional Access policy
that requires MFA.
You cannot delete it.  I tried.
Just ran MD-102 last week.
Everyone needs a cell phone.

My work around:  When students log into https://intune.microsoft.com or
https://entra.microsoft.com, choose the Phone # option to receive an SMS
code.
*Do NOT log out even though the lab steps say so.*
*If there is a need to log in as a different user, use InPrivate window in
Edge or Incognito mode in Chrome.*
Why?  After 3 logins, everyone is required to use the Authenticator app.

A pain, I know, but it is what it is.

Al Wills

**Comment by TommyKobber** [comment]
Read this: https://kongwhiteboards.blob.core.windows.net/mctdocs/MFA%20for%20Microsoft%20365%20and%20Dynamics%20365%20Tenants%20FAQ.pdf?sp=r&st=2024-04-02T15:25:37Z&se=2024-11-01T23:25:37Z&spr=https&sv=2022-11-02&sr=b&sig=eQHD7mH3Vbgb3vMwAjdqFjVLpK3g8Dr3yDzW2unIzCs%3D

**Comment by TommyKobber** [comment]
The whole course is due for a major update some time in May, so I don't think the current lab descriptions will be changed before that

**Comment by WigF1** [comment]
Lab 6 worked fine on Skillable. My students had no dramas.
