### ISSUE TITLE
LP 201, Exercise 2: Configuring Entra Hybrid Join missing steps to add MDM GPO and UPN

### ISSUE THREAD

**Issue by SkillableBB** [MicrosoftLearning/MD-102T00-Microsoft-365-Endpoint-Administrator#83]
#### Step 08

Description of issue
For Hybrid Active directory to successfully join, the MDM GPO [p1] and UPN [p2] need to be added; these steps are missing within the current manual.

[p1]

![gpo mdm-ebf186d6-0e78-42ca-a0b3-05937be12577](https://github.com/MicrosoftLearning/MD-102T00-Microsoft-365-Endpoint-Administrator/assets/94069201/f80c8c78-b576-4d42-8b51-de1b630c8b1e)

[p2]

![image-1](https://github.com/MicrosoftLearning/MD-102T00-Microsoft-365-Endpoint-Administrator/assets/94069201/f684a880-b27e-48a4-9389-a0ac549ef8bd)

**Comment by WigF1** [comment]
They don't need to be added in order for the Hybrid join to work. 

They would need to be added if you wanted the devices to be auto-enrolled into InTune, which is not part of the labs.

**Comment by MSFT-rstearman** [comment]
Closing for no further review needed.
