### ISSUE TITLE
Synchronizing Identities by using Microsoft Entra Connect Download file issue

### ISSUE THREAD

**Issue by ahsan296** [MicrosoftLearning/MD-102T00-Microsoft-365-Endpoint-Administrator#86]
# Module: 0102
#### Step: 03

**Description of issue:** 
When I paste this required link at browser "http://www.microsoft.com/en-us/download/details.aspx?id=47594" then it gives me **Internal Server Error**. The required link didn't work properly.

**Issue related Screenshot:**

![image](https://github.com/user-attachments/assets/b2a5aeba-d2af-4088-8892-b8558fe5dc82)

**Comment by MSFT-rstearman** [comment]
Thank you for bringing this to our attention. I will review this and make the necessary changes.

**Comment by ahsan296** [comment]
Thank you @MSFT-rstearman I am waiting for your reply.

**Comment by MSFT-rstearman** [comment]
This is a widespread issue and is currently working on getting it resolved. We currently don't have an ETA.

**Comment by ahsan296** [comment]
Ok Sure @MSFT-rstearman Thank You!

**Comment by ahsan296** [comment]
I have downloaded the new version of msi but it's not configured successfully. But when I used to configure with old version of msi then it's work fine:

![image](https://github.com/user-attachments/assets/d780890b-a235-4c6f-808e-1ec333a8cdae)

**Comment by MSFT-rstearman** [comment]
We have updated the Lab images to enable TLS 1.2. This will resolve the issues going on with Entra Connect.
