### ISSUE TITLE
Lab 0101 - Azure AD Sync requirements break the lab

### ISSUE THREAD

**Issue by WigF1** [MicrosoftLearning/MD-102T00-Microsoft-365-Endpoint-Administrator#87]
# Module: 01
## Lab/Demo: 01

Description of issue

Due to changes now being **enforced** for Azure AD Connect, students cannot install Azure AD Connect successfully without first enabling TLS1.2 by following the steps listed in the documentation here.

https://learn.microsoft.com/en-us/entra/identity/hybrid/connect/reference-connect-tls-enforcement

When you run the check script from that location on SEA-SVR1 this is the output:

![image](https://github.com/user-attachments/assets/9e15c2af-1a8c-4f13-aa28-6307852c9091)

The underlying image needs to be modified to have TLS1.2 enabled so we can avoid **every** single student having to perform the exact same steps for **every** single delivery.

**edit**

This is as of July 15 per https://learn.microsoft.com/en-us/entra/identity/hybrid/connect/reference-connect-version-history#looking-for-the-latest-versions

![image](https://github.com/user-attachments/assets/18c6c206-0290-477e-a596-448d4292a75c)

**Comment by MSFT-rstearman** [comment]
Thank you Steve, We will add these instruction steps to the labs.

**Comment by MSFT-rstearman** [comment]
Hey Steve, Which ALH are you using for your lab deployments? We are performing testing and have found that our images have TLS1.2 enabled on them.

**Comment by WigF1** [comment]
@MSFT-rstearman  Skillable.

**Comment by WigF1** [comment]
Those screenshots were taken from SEA-SVR1. I'm just doing some work prior to another delivery next week and neither SEA-SVR1 nor SEA-SVR2 had the reg keys.

**Comment by MSFT-rstearman** [comment]
Are you using a new instance or a saved one? When i reached out to Skillable, they stated that all new instances have been updated.

**Comment by WigF1** [comment]
As I typed my two previous replies, I was working with a brand new instance.

I'm delivering it again next week and **now** the VMs have it enabled by default, they did not previously.

![image](https://github.com/user-attachments/assets/384bc043-f908-4f98-9a0f-9cf739ce7f0b)
