### ISSUE TITLE
Licensing moving from Entra portal

### ISSUE THREAD

**Issue by WigF1** [MicrosoftLearning/MD-102T00-Microsoft-365-Endpoint-Administrator#89]
According to the warning on the non 365 admin portal licensing pages:

![image](https://github.com/user-attachments/assets/58cef41a-b0eb-4ad3-88b3-ce53b7dbaa89)

We should be **proactive** about changing any and all labs that have us license users to use the 365 Admin center. I think it is just 0101 and 0203 that need amending.

**Comment by WigF1** [comment]
The change has been delayed until September 09.

However, we still need to be **proactive** in changing the two labs listed above to direct students into the 365 admin center.

Has there been anything done @ MSL re either of these two labs?

**Comment by WigF1** [comment]
And licenses can no longer be assigned unless in the 365 Admin center. 

The lab steps need modifying.

**Comment by dpapkin** [comment]
Is anyoen fixing these changes? SO far dont labs 0101 and 0102 and there are some differences due to GUI drift and the changes ot the portals. Cant assign license directly using Entra portal anymore, must use Admin portal.

**Comment by WigF1** [comment]
@dpapkin I was hoping that by notifying the repo owners, they might want to be proactive in fixing things. It seems we're going to have fix things ourselves **again**.

**Comment by dpapkin** [comment]
> @dpapkin I was hoping that by notifying the repo owners, they might want to be proactive in fixing things. It seems we're going to have fix things ourselves **again**.

Things seem to have gone to hell in a handbag lately.

Sc-300 is even worse, unusable lab instructions. Just taught last week. Dreadful.

Who do we need to escalate to to get them to update these instructions to match the changes? We have HUGE batches of users in a project starting on November. They will complain big time.

**Comment by MSFT-rstearman** [comment]
pull request was merged to resolve this.
