### ISSUE TITLE
Change in terminology in Conditional access

### ISSUE THREAD

**Issue by hbud** [MicrosoftLearning/MD-102T00-Microsoft-365-Endpoint-Administrator#98]
# Module: 06
#### Step: 07

Description of issue

The lab says: Under Include choose the Select apps radio button, under the Select option select None, select Office 365 Exchange Online, and then click Select.
Terms have changed to: "select resources" and all cloud apps has changed to "all resources (formerly select apps)"
Repro steps:
![Untitled](https://github.com/user-attachments/assets/0a1ae29d-9c82-4933-b024-369e4c7e2e68)

**Comment by MSFT-rstearman** [comment]
changes have been made to correct this
